### ISSUE TITLE
How to solve this problem：The partition number of the source kafka topic is 5, but the partition number of the destination kafka topic is 1

### ISSUE THREAD

**Issue by Bruce2jiang** [linkedin/brooklin#649] opened 2019-09-18 08:14 UTC
How to solve this problem：The partition number of the source kafka topic is 5, but the partition number of the destination kafka topic is 1

**Comment by ahmedahamid** [comment] 2019-09-18 18:14
@Bruce2jiang If this question is about the Kafka MirrorMaker connector, please check out the `system.destination.identityPartitioningEnabled` option on the [connector's wiki page](https://github.com/linkedin/brooklin/wiki/Kafka-MirrorMaker-Connector).

**Comment by ahmedahamid** [comment] 2019-09-21 00:24
Closed as duplicate of #651

**Closed by ahmedahamid** 2019-09-21 00:24 UTC
Labels: question
